src/bin.rs
src/vfs_watch.rs

The infinite loops that are keeping the threads alive are what really was killing CPU usage. Sleeping for 100 ms seems to work. Not sure how exactly rust async works right now, so this may cause delay of up to 1 second before polling, but filesystem already uses that delay.
Preferably, the webserver also just uses the main thread, instead of creating its own. Busy polling is still bad.

Fix #21: High CPU usage in a small project

---

CHANGELOG.md
server/src/rbx_snapshot.rs
test-projects/localization/expected-snapshot.json
test-projects/localization/src/integers-bug-145.csv

Fixes #145.
After filing a bug on the csv crate (https://github.com/BurntSushi/rust-csv/issues/151) it became pretty clear that there isn't really a way for Serde to losslessly decode the localization format Roblox expects for me.
This PR rewrites the CSV parser to manually trawl each record and map them into structs. I added a new regression test for #145 and made sure all existing tests continued to pass.

Rewrite CSV conversion to dodge Serde

---

CHANGELOG.md
server/src/rbx_snapshot.rs
server/tests/snapshot_snapshots.rs
test-projects/json_model/default.project.json
test-projects/json_model/expected-snapshot.json
test-projects/json_model/src/children.model.json
test-projects/json_model/src/explicit.model.json
test-projects/json_model/src/implicit.model.json

Closes #31. Closes #144.
This PR makes JSON model files more friendly by letting them use implicit property values.
Previously, your `.model.json` file might look like:
```json
{
"Name": "explicit",
"ClassName": "StringValue",
"Properties": {
"Value": {
"Type": "String",
"Value": "Hello, world!"
}
}
}
```
Now, for many property values, you can instead write:
```json
{
"Name": "explicit",
"ClassName": "StringValue",
"Properties": {
"Value": "Hello, world!"
}
}
```
This change happened for project files a few releases ago, but the JSON model format wasn't updated to match.

Support implicit values in JSON models

---

server/src/rbx_snapshot.rs
test-projects/meta_files/expected-snapshot.json
test-projects/meta_files/src/DisableMe.meta.json
test-projects/meta_files/src/LocalizationTable.csv
test-projects/meta_files/src/LocalizationTable.meta.json
test-projects/meta_files/src/RobloxInstance.meta.json
test-projects/meta_files/src/RobloxInstance.rbxmx
test-projects/meta_files/src/StringValue.meta.json
test-projects/meta_files/src/StringValue.txt

*Truly* closes #123.
`Thing.server.lua` would have a `.meta.json` of `Thing.meta.json`, as said by LPG on Discord.

Support for .meta.json files other than init

---

src/change_processor.rs
src/common_setup.rs
src/serve_session.rs
src/snapshot_middleware/csv.rs
src/snapshot_middleware/dir.rs
src/snapshot_middleware/json_model.rs
src/snapshot_middleware/lua.rs
src/snapshot_middleware/middleware.rs
src/snapshot_middleware/mod.rs
src/snapshot_middleware/project.rs
src/snapshot_middleware/rbxlx.rs
src/snapshot_middleware/rbxm.rs
src/snapshot_middleware/rbxmx.rs
src/snapshot_middleware/txt.rs
src/snapshot_middleware/user_plugins.rs

This PR strips out any case where we're accepting a `&mut Vfs` as well as any case where we're holding a `Mutex<Vfs>`. These should no longer be necessary with #259, which this PR has as a prerequisite.

Remove outer VFS locking

---

src/change_processor.rs
src/common_setup.rs
src/serve_session.rs
src/snapshot_middleware/csv.rs
src/snapshot_middleware/dir.rs
src/snapshot_middleware/json_model.rs
src/snapshot_middleware/lua.rs
src/snapshot_middleware/middleware.rs
src/snapshot_middleware/mod.rs
src/snapshot_middleware/project.rs
src/snapshot_middleware/rbxlx.rs
src/snapshot_middleware/rbxm.rs
src/snapshot_middleware/rbxmx.rs
src/snapshot_middleware/txt.rs
src/snapshot_middleware/user_plugins.rs
src/vfs/fetcher.rs
src/vfs/noop_fetcher.rs
src/vfs/real_fetcher.rs
src/vfs/test_fetcher.rs
src/vfs/vfs.rs
src/web/ui.rs

Each commit in this PR can be looked at independently, I made these changes as an incremental refactor of the VFS implementation.
This PR refactors all of the methods on `Vfs` from accepting `&mut self` to accepting `&self` and keeping data wrapped in a mutex. This builds on previous changes to make reference count file contents and cleans up the last places where we're returning borrowed data out of the VFS interface.
Once this change lands, there are two possible directions we can go that I see:
* Conservative: Refactor all remaining `&mut Vfs` handles to `&Vfs`
* Interesting: Embrace ref counting by changing `Vfs` methods to accept `self: Arc<Self>`, which makes the `VfsEntry` API no longer need an explicit `Vfs` argument for its operations.

VFS Improvements

---

src/snapshot_middleware/dir.rs
src/snapshot_middleware/json_model.rs
src/snapshot_middleware/lua.rs
src/snapshot_middleware/rbxlx.rs
src/snapshot_middleware/rbxm.rs
src/snapshot_middleware/rbxmx.rs
src/snapshot_middleware/txt.rs

Split off of #268.
This finishes the transition to the new `InstanceContext` concept by attaching it to each instance as necessary.

Attach context to instances from snapshots

---

Cargo.toml
src/cli/build.rs
src/cli/mod.rs

Closes #92.
This PR refactors the build command slightly to add a `--watch` argument. When set, Rojo will continuously rebuild the model when any of its inputs change.

Implement 'rojo build --watch'

---

CHANGELOG.md
rojo-test/build-test-snapshots/rojo_test__build_test__json_as_lua.snap
rojo-test/build-tests/json_as_lua/default.project.json
rojo-test/build-tests/json_as_lua/make-me-a-script.json
rojo-test/src/build_test.rs
src/lib.rs
src/lua_ast.rs
src/snapshot_middleware/error.rs
src/snapshot_middleware/json.rs
src/snapshot_middleware/mod.rs
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__json__test__instance_from_vfs.snap

Closes #148.
This PR makes Rojo process otherwise unknown JSON files by turning them into `ModuleScript` instances that return the equivalent structure in Lua. This is done with a module containing a small subset of a Lua AST, and transcoding from `serde_json::Value`.
This didn't turn out _quite_ as well as I was hoping. Interaction between snapshot middleware is still kind of ill-defined, and so this new middleware has to explicitly avoid turning `.meta.json` files into instances.
* Tests

Implement support for turning .json files into Lua modules

---

CHANGELOG.md
src/cli/mod.rs
src/cli/serve.rs
src/web/mod.rs

127.0.0.1 is a loopback interface, and only works on the same host
binding to 0.0.0.0 will allow connections from other hosts and will actually give purpose to the IP field on the plugin
i have a laptop running linux (so cannot use studio) and another host running windows, where i RDP to for studio - i was wondering why it couldn't connect. rebuilt with these changes and it can now listen to the linux host
previously:
```
[Rojo-Warn] Disconnected from an error: Couldn't connect to the Rojo server.
[Rojo-Warn] Make sure the server is running — use 'rojo serve' to run it!
```
now:
*using stable, but change is universal*

change server bind address

---

CHANGELOG.md
src/snapshot_middleware/project.rs

Closes #391.
This pull makes the usage of "Name"/"Parent" in $properties ignored, with a warning to the user that said properties cannot be set. Maybe exiting with an error would be better?

Block usage of "Name" or "Parent" in $properties

---

rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_all-2.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_info.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_subscribe.snap
rojo-test/serve-tests/empty_json_model/default.project.json
src/change_processor.rs
src/snapshot_middleware/json_model.rs
src/snapshot_middleware/mod.rs
tests/tests/serve.rs

Do not validate .model.json files with no content/whitespace only

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
src/cli/build.rs
src/message_queue.rs
src/web/api.rs
src/web/mod.rs
src/web/ui.rs
src/web/util.rs

This has been a long time coming.
Rojo's HTTP code pre-dates Rust's support for async/await. We can simplify the code a lot by switching to async/await and dropping a lot of the long-winded Hyper code that I wrote originally.
That's what this PR does!
Everything should be functionally the same. I've tested it manually a little bit and of course our automated end-to-end tests still pass.

Upgrade to Tokio 1.x, futures 0.3, Hyper 0.14, etc

---

plugin/src/Reconciler/reify.lua
plugin/src/Types.lua

The reconciler's reify function was still using the old value format for Refs, causing Ref properties to fail to sync. This PR also updates the ApiValue type to use the new value format (this caused problems when type checking was enabled).

Fix Ref reification

---

plugin/src/Reconciler/decodeValue.lua
plugin/src/Reconciler/diff.lua

I had ran into an issue with Refs in #465 on an older version of Rojo, and was guided to try out the latest version and still had issues. These parts of the plugin were relying on the old Rojo protocol and I've now updated them.
Regarding the comment I left on diff.lua#78, I've described one instance that can cause the table to be empty in #467.
*The unverified is because my GPG for Windows is kinda messed up. The next commit is verified me!*

Update nil Ref check and property decode warning to new Rojo protocol

---

plugin/src/App/StatusPages/NotConnected.lua

This pull request makes it so that the host and port are not cleared when connecting.
Closes #103

Remember sync connection settings.

---

Cargo.lock
plugin/rbx_dom_lua/database.json
src/cli/upload.rs

Closes #486 by providing a ``--api_key`` along with ``--universe_id`` in place of ``--cookie``. Universe ID is required in order to use the open cloud api.
So new upload commands will look like ``rojo upload --api_key <API_KEY> --asset_id <PLACE_ID> --universe_id <UNIVERSE_ID> [project file]``
Instead of ``rojo upload --cookie <COOKIE> --asset_id <PLACE_ID> [project file]``
This was made with an accumulative ~3 hours of experience with rust, so I'm sure things could be done better and I'm open to suggestions. Most notably lines 48-68.

Support the new Open Cloud API

---

CHANGELOG.md
src/cli/serve.rs
src/project.rs
src/serve_session.rs

Close #447. Gives support for specifying the default address in the .project.json file.
Running rojo serve with the ``--address`` flag will still use the passed address rather than the address specified in .project.json.
Example entry:
```json
{
"name": "serve-address-example",
"serveAddress": "127.0.0.1",
"tree": {
"$className": "DataModel"
}
}
```

Add ability to specify address in default.project.json

---

CHANGELOG.md
src/cli/mod.rs
src/cli/sourcemap.rs

This PR implements a new `sourcemap` command which produces an instance tree in JSON format in the following shape:
```json5
{
// Equivalent to instance.Name in Roblox
"name": "...",
// Equivalent to instance.ClassName in Roblox
"className": "...",
// Array of existing file paths that contributed to the creation of this instance
"filePaths": ["src/path/init.lua", "src/path/init.meta.json"],
// Array of children with the same structure
"children": []
}
```
This enables new & interesting use cases, as well as consistency in other tools/apps when using Rojo.
* Tools like [luau-analyze-rojo](https://github.com/JohnnyMorganz/luau-analyze-rojo) and [Roblox LSP](https://github.com/NightrainsRbx/RobloxLsp) should no longer need to do their own parsing of file structures and suffixes to get the …

Implement sourcemap CLI command

---

plugin/src/App/StatusPages/NotConnected.lua
plugin/src/App/init.lua
plugin/src/ServeSession.lua

Fixes the following issues that I missed in #537:
My sincere apologies!

Bugfix: PluginAction spam causing errors

---

src/cli/sourcemap.rs
src/serve_session.rs

Simple fix to handle `rojo sourcemap` when a project file is not given correctly. Previous behavior was removing one level of directories too much inside the sourcemap if the project file path was not given.

Fix sourcemap command not stripping paths correctly

---

plugin/src/App/init.lua

When changing a setting, the UI updates (checkbox will fill/empty) but the **setting does not actually change** or take effect.
This is because the settings page and the app are consuming two different settings tables in memory and so the settings page doesn't impact the table that the app will actually use.
This is an slip during the refactor of App in #537, as we made the functional wrapper create settings and accidentally left another in stateful render.
A very simple fix- just remove the old unused duplicate, and we're good to go.
If the PR seems large, view the diff ignoring whitespace as I had to alter the indentation of a lot of components that are no longer nested in the provider.

Bugfix: Settings not working

---

.github/workflows/ci.yml
.github/workflows/release.yml

This PR ports the release workflow from Aftman, with a couple tweaks to keep the existing VS Code Rojo extension working.
This is how we will create releases for Rojo in the future.
Artifacts from the last release workflow, which are uploaded manually:
Artifacts from the new release workflow, which are uploaded completely automatically:

New release workflow

---

Cargo.lock
Cargo.toml
src/change_processor.rs
src/cli/build.rs
src/serve_session.rs
src/snapshot/instance_snapshot.rs
src/snapshot/patch_apply.rs
src/snapshot/patch_compute.rs
src/snapshot/tests/compute.rs
src/snapshot/tree.rs
src/snapshot_middleware/rbxm.rs
src/snapshot_middleware/rbxmx.rs

This PR relies on stuff currently unreleased in rbx-dom libraries. All of these fixes combined should result in a 3-4x speedup for large Rojo projects.

Major Performance Improvements

---

rojo-test/build-test-snapshots/end_to_end__tests__build__issue_546.snap
rojo-test/build-tests/issue_546/README.md
rojo-test/build-tests/issue_546/default.project.json
rojo-test/build-tests/issue_546/hello/init.client.lua
rojo-test/build-tests/issue_546/hello/init.meta.json
src/snapshot_middleware/dir.rs
src/snapshot_middleware/lua.rs
tests/tests/build.rs

Defer application of `init.meta.json` until after init Lua files.

---

Cargo.lock
Cargo.toml

Fixes #557. I can't seem to get the `cargo test` command passing on either the base or this commit. I suspect that issue is related to my local development setup, and if CI is green it should be fine. I also have tested the debug build in my workflow and am no longer seeing the same errors that I was in that issue.

Update rbx_binary to 0.6.5, fixes #557

---

.github/workflows/release.yml

ubuntu-latest uses Ubuntu 20.04, this causes issues with glibc as older versions of ubuntu/other distros use an older version.
This is fixed by building the release binary on `ubuntu-18.04`, which uses a version of glibc more widely available.
Ref: https://github.com/JohnnyMorganz/StyLua/pull/444
https://github.com/JohnnyMorganz/StyLua/pull/445

Change linux release runner to use `ubuntu-18.04`

---

src/cli/serve.rs

This pull request just fixes the CLI bug on rojo-rbx/rojo#555
Here is a screenshot of the changes on the output

Added address reference to CLI output

---

plugin/src/Assets.lua

The notification sound for the plugin notifications causes the game to summon an error due to no experience permissions with no way to grant permission. This is due to the new audio policy update.

Change Notification sound to generic sound

---

plugin/src/ServeSession.lua

Fixes issue #579.
To debug, I put a traceback into `__stopInternal` and performed the repro steps from issue #579. I saw where the call came from, and then added an if statement there (the API promise) to prevent it from firing stop after the session is already stopped.
After this change, performing the repro steps leads to no errors or warnings as expected.

Fix errors after session already ended

---

rojo-test/build-test-snapshots/end_to_end__tests__build__init_csv_with_children.snap
rojo-test/build-tests/init_csv_with_children/default.project.json
rojo-test/build-tests/init_csv_with_children/src/init.csv
rojo-test/build-tests/init_csv_with_children/src/other.csv
src/snapshot_middleware/csv.rs
src/snapshot_middleware/mod.rs
tests/tests/build.rs

feature init csv

---

CHANGELOG.md
src/cli/sourcemap.rs

Adds support for `--watch` on sourcemap generation, to automatically regenerate sourcemap on changes.
I went ahead and did some drive-by fixes for some clippy warnings too. Also added a call to `forget` similar to how `rojo build` does it. Let me know if you want this reverted and in a separate PR though

Add `--watch` to sourcemap generation

---

plugin/src/App/StatusPages/Error.lua

It was requested that error messages be copyable for easier support and debugging. Being able to double click the message, hit Ctrl+C, and then Google it is much nicer than having to retype it up by hand. Also allows you to drag to select just part of it.
This is a very small and easy change, and there's no downside to it.

Make error messages copyable

---

plugin/src/Reconciler/diff.lua

```
The current identity (5) cannot Class security check (lacking permission 6)
PluginDebugService.user_Rojo.rbxm.Rojo.Plugin.Reconciler.diff:118 function diffInternal
```
Apparently some Instances don't like it when you read a property. Wrapping our check in a pcall resolves this.

Fix security permission error

---

.github/workflows/release.yml
aftman.toml

replaced forman with afterman for builds
to fix the issues with foreman not building specific builds.
I still use foreman for the creation of the plugin
node:
In some of my test the Build (aarch64-apple-darwin) failed since I exceeded the api limit Idk if this issue would reappear for you as well but if I rerun it it then works.
error:
Aftman error: Unexpected GitHub API response: {"message":"API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

fix release action with aftman

---

plugin/src/App/init.lua

When you put in the URL `https://example.com`, it would try to send a request to `http://https://example.com` instead, which would cause an "InvalidUrl" error. This fixes the error by only implicitly adding `http://` if a protocol is not otherwise specified.
This change is necessary for a project I'm working on that serves a Rojo project over https (via an SSL termination proxy) in order to prevent man in the middle attacks.

Support explicitly specifying http or https protocol in plugin

---

plugin/src/App/Components/BorderedContainer.lua
plugin/src/App/Components/Checkbox.lua
plugin/src/App/Components/IconButton.lua
plugin/src/App/Components/TextButton.lua
plugin/src/App/Components/Tooltip.lua
plugin/src/App/StatusPages/Connected.lua
plugin/src/App/StatusPages/Error.lua
plugin/src/App/StatusPages/NotConnected.lua
plugin/src/App/StatusPages/Settings/init.lua
plugin/src/App/init.lua

Adds tooltips to the buttons. This may seem a bit "extra" for now, but as the Rojo workflow gets more complex (two-way, etc) the single-word buttons aren't enough to convey the meaning behind them, necessitating tooltips. Superfluous tips will likely never been seen by users anyway (since they are unlikely to hover) so there's no detriment to adding them even to simple buttons.
Features:
- Easy usage via Roact component
- Auto size and position using available space
- Tail triangle points at your mouse
- Follows theme and style
- Supports multiple canvases and arbitrary tips
Tech breakdown:
`Tooltip.Provider` wraps the App, cascading the Context everywhere. `Tooltip.Canvas` renders any tip popups- it is done this way because Sibling ZIndex means the popups must be in a separate layer …

Add tooltips to buttons

---

aftman.toml
plugin/src/Config.lua
plugin/wally.lock
plugin/wally.toml

Not entirely sure but I looked at some of the code and it seems like this should fix the wrong version showing up, "7.2.1" instead of "7.3.0", hopefully this works...

Fix wrong version of Rojo displaying in studio.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli/sourcemap.rs

This PR brings two performance improvements to the `rojo sourcemap` command:
-   Use `rayon` with a small threadpool to parallelize sourcemap generation while still keeping startup cost very low
-   Remove conversions to owned strings and use lifetimes tied to the dom instead, which mostly improves performance with the `--include-non-scripts` flag enabled
From my personal testing on an M1 mac this decreases the sourcemap generation time of our games by 2x or more, from ~20ms to ~8ms on one project and ~30ms to ~15ms on another. Generation is pretty fast to begin with but since sourcemaps are heavily used in interactive tools (like luau-lsp) a difference of a couple frames can be great for ux.

Sourcemap performance improvements

---

plugin/src/ApiContext.lua
plugin/src/ServeSession.lua

When a session is disconnected, the apiContext long-polling for messages continues until resolved/rejected. This means that even after a session is disconnected, a message can be received and handled.
This leads to bad behavior, as the session was already cleaned up and the message cannot be handled correctly. The instance map was cleaned up upon disconnect, so it will warn about unapplied changes to unknown instances. (Like #512)
It's very easy to repro:
Connect a session, disconnect it, then save a change.
https://github.com/rojo-rbx/rojo/assets/40185666/846a7269-7043-4727-9f9c-b3ac55a18a3a
-----------
This PR fixes that neatly by tracking all active requests in a map, and cancelling their promises when we disconnect.

Fix disconnected session activity

---

plugin/src/App/Components/PatchVisualizer/DomLabel.lua
plugin/src/App/Components/VirtualScroller.lua
plugin/src/App/StatusPages/Connected.lua
plugin/src/App/init.lua

Clicking on the "X changes X ago" message opens up a handy diff visualizer to see what those changes were. However, it had quite a few issues that needed fixing.
- Disconnecting a session with it expanded caused an error as it tried to read the serveSession that no longer exists during the page fade transition. (#671)
- Resolved by converting to stateful component and holding the serveSession during the lifetime to ensure it can render the last known changes during the fade transition
- Leaving it open while new changes are synced did not update the visualizer
- The patch data was piggybacking on an existing binding, which meant that new patches did not trigger rerender.
- Resolved by converting to state
- Also made some improvements to that old binding
- Moved from app to connected page …

Fix the diff visualizer of connected sessions

---

.gitmodules

Why if you want to use ssh you need todo more setup aka add a ssh key into github while with https you don't have to do the extra work aka makes rojo easier to contribute to.

Change gitmodules from ssh to https

---

.github/workflows/release.yml

Fixes macOS aarch64 builds not actually outputting x86 binaries by specifying the `--target` flag during compilation in the release workflow. These are the same changes as [this PR in Aftman](https://github.com/LPGhatguy/aftman/pull/34), which had the same issue, and uses the same workflow.

Fix compilation target in release workflow

---

CHANGELOG.md
plugin/src/App/init.lua
plugin/src/PatchSet.lua

Closes #672.
Skips the user confirmation if the patch contains only a datamodel name change.
I decided to build generic PatchSet utility functions in case we need to use similar logic in the future, in addition to maintaining clear division of duties. The app code shouldn't be too dependent upon patch internal structure when we can avoid it.

Skip confirming patches that only contain a datamodel name change

---

CHANGELOG.md
plugin/src/ServeSession.lua

Closes #113.
Does what it says on the tin. When you try to sync a non-place project, it gives a clear message instead of crashing.

Add protection against syncing non place projects

---

plugin/src/App/Components/PatchVisualizer/init.lua

When an object is deleted in a patch, it is either represented with an ID or an Instance. On initial sync, removals are instances since the map does not contain those instances. Later removals of managed objects use an ID. The patch visualizer only handled instances, so this fixes that.
Closes #710.

Handle strings and instances in patch removes for visualizer

---

CHANGELOG.md
plugin/src/App/StatusPages/Connected.lua
plugin/src/App/init.lua

Closes #721, #690, #554.
By adding buttons to the connected page, the Rojo UI is more consistent across pages, image outages won't make actions invisible, and ambiguous iconography is not an issue.

Add buttons on connected page

---

CHANGELOG.md
plugin/src/App/Components/Tooltip.lua

Tooltips only triggered based on mouse movement, but if the hover trigger moved out from under a stationary mouse then the tooltip remained. This was really irking me, so I redid the tooltip logic to solve this.
https://github.com/rojo-rbx/rojo/assets/40185666/433c748b-201a-4ed1-a460-383f05340d00
This doesn't technically support rotated triggers, but we have no need for that so I'm not going to over complicate the math when it won't provide benefit.

Improve tooltip behavior

---

src/snapshot/instance_snapshot.rs
src/snapshot/patch_apply.rs
src/snapshot/patch_compute.rs
src/snapshot/tests/compute.rs
src/snapshot/tests/snapshots/librojo__snapshot__tests__compute__add_child.snap
src/snapshot_middleware/json_model.rs
src/snapshot_middleware/project.rs
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__csv__test__csv_from_vfs.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__csv__test__csv_with_meta.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__dir__test__empty_folder.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__dir__test__folder_in_folder.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__json__test__instance_from_vfs.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__json_model__test__model_from_vfs.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__json_model__test__model_from_vfs_legacy.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__lua__test__client_from_vfs.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__lua__test__module_from_vfs.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__lua__test__module_with_meta.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__lua__test__script_disabled.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__lua__test__script_with_meta.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__lua__test__server_from_vfs.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__project_from_direct_file.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__project_path_property_overrides.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__project_with_children.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__project_with_path_to_project.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__project_with_path_to_project_with_children.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__project_with_path_to_txt.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__project_with_resolved_properties.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__project_with_unresolved_properties.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__txt__test__instance_from_vfs.snap

Ref now is an optional inside, so it's redundant to have an option wrapping an option. The only snapshots that were changed were any that had a Ref within (from none to zeroed). Some also had some newlines added in the end.
Aside:
Since Ref is a nullable type, I'm worried about the change. For example, it's easy for someone to insert a null ref into any map where it's expected to be non-null, like in a PatchSet.

Removed InstanceSnapshot snapshot_id's redudant Ref.

---

CHANGELOG.md
plugin/src/App/Components/PatchVisualizer/ChangeList.lua
plugin/src/App/Components/PatchVisualizer/DomLabel.lua
plugin/src/App/Components/PatchVisualizer/init.lua
plugin/src/App/StatusPages/Confirming.lua
plugin/src/App/StatusPages/Connected.lua
plugin/src/App/init.lua
plugin/src/PatchTree.lua
plugin/src/Reconciler/init.lua

Closes #714.
The patch visualizer logic had a serious flaw: it was given a patch but the state of the world may be before or after that patch was applied, making it potentially impossible to build a tree from the patch data.
This PR totally reworks that, and makes some other improvements while we're at it.
- Reconciler now has precommit and postcommit hooks for patch applying
- This is used to compute a patch tree snapshot precommit and update the tree metadata postcommit
- Could be useful for more things down the line! Maybe patch preprocessing middleware? Who knows
- PatchVisualizer can now display Removes that happened during sync
- It was previously missing because the removed objects no longer existed so it couldn't get any info on them (This is resolved because the info is gotten in …

Rework patch visualizer with many fixes and improvements

---

plugin/src/ApiContext.lua
plugin/src/ServeSession.lua

Closes #734.
Rojo's main sync loop was a recursive promise method, which may have been obscuring issues. Additionally, ApiContext would choose to silently hang forever where we wanted to silence an error after disconnect, which may have been happening erroneously and causing silent hangs.
I have rewritten these so that ServeSession is non recursive and also knows how to handle ApiContext errors correctly in any state so that the hanging promise solution is no longer needed. Also, it may have not been needed ever since I added promise cancelling to ApiContext, but either way it's certainly not needed now.

Improve Rojo sync reliability

---

CHANGELOG.md
benches/build.rs
src/cli/build.rs

Resolves #715. 
It will not output to the correct place if the user configures the location of their plugin folder. That functionality would have to be added to `roblox_install`. I haven't looked into whether it's possible or not yet.
Here is what the output looks like:
I wasn't able to get the error cases to say "rojo build" in the usage section.

Add plugin build flag

---

CHANGELOG.md
src/resolution.rs

Given how unambiguous `Font` as a datatype actually is, it makes not very much sense to require people use the fully qualified syntax for `FontFace` and any other properties that come up. So, this PR adds a new ambiguous syntax that supports it.
Long-term, I think we should reconsider our strategy for font families to make it more obvious how to set them (maybe use an enum instead of a raw string?) but that's an issue for another day.

Support ambiguous syntax for Font properties

---

CHANGELOG.md
plugin/src/PatchTree.lua

When building the tree, I've implemented a few improvements:
- We no longer traverse the full ancestry for every leaf node- we exit early when we find a node that already exists
- We no longer search the entire tree to see if a node id exists before creating one with that id, we just check if is in the map

Fix PatchTree performance issues

---

CHANGELOG.md
plugin/src/App/StatusPages/Confirming.lua
plugin/src/App/StatusPages/Connected.lua

Due to an implementation detail with Roact (it calls `Destroy` on unmount), we have to recreate the source diff viewer plugin gui everytime a patch is visualized.
This ends up causing trouble because Studio doesn't like it if you create a plugin with the same ID. This was causing the plugin to die when trying to visualize a source diff. 
I have no idea why this is the case, but this fixes that from what my tests have showed. 🤷🏼

Don't override initial state for source diff view

---

CHANGELOG.md
src/resolution.rs

The last release of rbx_dom had support for `Terrain.MaterialColors`. This allows it to be specified directly instead of only via the fully-qualified syntax.

Add ambiguous value support for MaterialColors

---

CHANGELOG.md
src/snapshot_middleware/project.rs

Services, `StarterPlayerScripts`, and `StarterCharacterScripts` are currently special-cased to allow them to be specified in project files without a classname. This does the same to `Terrain` since it's a singleton in the same style as those.

Allow `Terrain` to be included in projects without a classname

---

plugin/rbx_dom_lua/EncodedValue.lua
plugin/rbx_dom_lua/EncodedValue.spec.lua

Fixes a problem where the MaterialColors Lua encoder would return nothing
(also has some changes to the EncodedValue test module, I guess they weren't carried over last time we updated rbx_dom_lua?)

Update rbx_dom_lua to rojo-rbx/rbx-dom@7b03132

---

src/cli/build.rs

I found out clap has a `conflicts_with` option we can use to remove a custom error.

Use `conflicts_with` for build flags

---

plugin/src/App/Components/Studio/StudioPluginGui.lua
plugin/src/App/StatusPages/Confirming.lua
plugin/src/App/StatusPages/Connected.lua
plugin/src/App/init.lua

Because Roact will destroy and recreate a plugin widget if it unmounts and remounts, Studio will complain about making a new widget with the same ID as the old one.
The simplest solution is to just use GUIDs so we never have to worry about this again. The ID is used internally for storing the widget's dock state and other internal details, so we don't want *all* our widgets to use GUIDs, only the ephemeral popup ones.

Use GUIDs for ephemeral PluginWidgets

---

.git-blame-ignore-revs

adds stylua pr to ignore so it doesn't show on git blame history

Create .git-blame-ignore-revs & Add Stylua pr

---

src/cli/mod.rs

LPG is at the moment listed by name and email in the `help` for Rojo. We should probably remove that before cutting a new release.

Don't include package author in CLI help

---

CHANGELOG.md
plugin/src/Config.lua

I made an oopsie and as a result versions of the plugin with metadata won't run. This fixes that.

Properly handle build metadata in semver parsing in plugin

---

CHANGELOG.md
src/cli/sourcemap.rs

This PR implements a mechanism for avoiding unnecessary sourcemap re-creation in `rojo sourcemap --watch`.
Consumers of `rojo sourcemap --watch` will no longer see new sourcemaps when changes to script sources and other properties occur, or when instances that have been ignored are changed, neither of which would actually make for changes in the sourcemap JSON body itself. 
This massively benefits tools such as [luau-lsp](https://github.com/JohnnyMorganz/luau-lsp) and [rojo-viewer](https://github.com/filiptibell/rojo-viewer) that would previously need to parse sourcemaps every time the user makes changes to the contents of a script or other source file, which tend to be the most common operations.
The approach taken here is intentionally conservative - we could reasonably track refs and …

Skip sourcemap generation when unaffected by changes in watch mode

---

plugin/src/PatchTree.lua

While I was testing #803, I discovered that `PatchTree.build` can create malformed `changeList` entries when a property decode fails. This causes errors when other parts of the system (such as `DomLabel`) attempt to interact with them. The core of the problem is that we're using `next` to obtain prop type-value pairs from the encoded property values in the incoming patch. `next` returns multiple values (in this case, the type followed by the value), which are then passed as-is to `addProp` or the table cons. What we want instead is to only pass the prop value.
This PR simply uses a `select` to only pass the prop value. I can also assign the result of `next` to variables in these cases if we think `select` is too ugly...

Fix PatchTree incorrect changeList entries on decode failure

---

plugin/src/ServeSession.lua

These warnings always appear for properties like `Capabilities`, `SourceAssetId`, etc. and tend to scare users who are syncing models. This information is now surfaced in the patch visualizer, so I think these warnings can be demoted to debug logs.

Demote unapplied patch warnings to debug logs

---

Cargo.lock
Cargo.toml

Bumps rbx_binary's version to 0.7.3 to bring in the missing `SecurityCapabilities` serialization fallback default

Bump rbx_binary to 0.7.3

---

CHANGELOG.md
plugin/rbx_dom_lua/customProperties.lua

Brings over some changes to rbx_dom_lua to validate attribute names before calling `Instance:SetAttribute`. This should prevent Rojo from falling over when it attempts to sync an attribute with an invalid name.

 rbx_dom_lua rojo-rbx/rbx-dom@440f3723 (attribute validation) 

---

plugin/src/preloadAssets.lua

`gatherAssetUrlsRecursive` now returns asset URLs deeper than one layer.

Fix preloading assets

---

tests/rojo_test/serve_util.rs

Right now, serve tests will fail when Rojo is built with the FSEvent backend. The cause is essentially due to the fact that `/var` (where temporary directories for serve tests are located) on macOS is actually a symlink to `/private/var`. Paths coming from FSEvent always have symlinks expanded, but Rojo never expands symlinks. So, Rojo's paths during these tests look like `/var/*` while the FSEvent paths look like `/private/var/*`. When Rojo's change processor receives these events, it considers them outside the project and does not apply any changes, causing serve tests to time out.
To work around this, we can call `Path::canonicalize` before passing the project path to `rojo serve` during serve tests. Rojo does need to better support symlinks (which would also solve the problem), but I …

Fix broken serve tests on macOS

---

.github/workflows/ci.yml

This PR adds macOS and Windows jobs to the CI workflow. This allows us to see when changes break functionality on any supported platform, which is particularly important for changes that involve the file system or file watcher.

Run CI workflow on Windows and macOS

---

src/change_processor.rs
tests/tests/serve.rs

This is a fairly important test verifying whether the action of moving a folder into a watched folder is correctly detected and processed. It was disabled in https://github.com/rojo-rbx/rojo/commit/b43b45be8f2eb01161a389afeab56749fa82e459. The fact that it failed indicates a possible bug in change processing, so in this PR, I'll re-enable the test, investigate why it fails, and fix it.

Fix move_folders_of_stuff

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/memofs/CHANGELOG.md
crates/memofs/Cargo.toml
crates/memofs/src/std_backend.rs

This PR makes a few changes to the file watching component of memofs' `StdBackend` to address performance problems on macOS. Closes #815 and closes #609. The amount of code churn here is unfortunate, but we haven't had a maintainer who works on macOS until now.
First, I downgraded back to Notify 4 by reverting #816. The reason for this is the fact that Notify 6's debouncer provides incorrect results when using the FSEvents backend. Specifically, FSEvents under some circumstances emits a Create event immediately followed by a Remove event for file deletions [???], which Notify 6's debouncer then collates into zero events, never reporting any changes. Notify 4's debouncer does not have this problem.
Because the raw events can be quite noisy, we do need some form of debouncing to avoid …

Downgrade to Notify 4, use FSEvents, use minimal recursive watches

---

CHANGELOG.md
plugin/src/App/Components/PatchVisualizer/DisplayValue.lua

Closes #757.
Old:
New:
Down the line, I do aim to replace the simple string representation of tables with a more visual spreadsheet-esque UI, but this is an easy improvement immediately.

Improve visualization for arrays

---

.github/workflows/ci.yml

Windows and macOS runners consume GitHub Actions minutes at [2x and 10x the rate of Linux runners, respectively](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers). This is a bit concerning now that there are two Windows jobs and two macOS jobs, introduced in #825. 
This PR aims to reduce the cost by:
* Adding [rust-cache](https://github.com/Swatinem/rust-cache/) to reduce the amount of time spent. I'm aware there were some concerns raised about CI caches in general in #496 - are they still a blocker?
* Removing the unnecessary Windows and macOS MSRV build jobs. If an MSRV build fails on one platform due to usage of new language features, then it will fail on all of them.
@Kampfkarren may have to change this …

Conserve CI minutes via cache, skip macOS+Windows MSRV builds

---

CHANGELOG.md
plugin/src/App/init.lua

If the sync lock is claimed in Team Create, the user cannot sync. Therefore, a sync reminder notification is unhelpful as it is calling to an invalid action.

Don't remind to sync if the lock is claimed

---

src/project.rs

Right now, if someone runs `rojo fmt-project` on a project that doesn't have `emitLegacyScripts` specified, it will emit a file with the default value (`true` right now). This is undesirable because it forces users into specifying a redundant field if they want to format their project.
This PR fixes that by simply removing the default for the field from Serde. Since we specify a default when we read it anyway, this has no impact on actual usage but makes `fmt-project` behave the same between 7.3 and 7.4.

Don't serialize `emitLegacyScripts` if it's `None`

---

build.rs

In #794, I changed the build script to guarantee that Rojo's plugin and CLI had the same major and minor version. In hindsight, this was a mistake though because it allows things like build metadata and pre-releases to slide through.
This changes that check to just check that they're absolutely identical because there's no reason that we should ever bundle an out of date plugin with the CLI.

Ensure plugin and Cargo version match exact at compile-time

---

plugin/src/PatchTree.lua

Closes #842. Includes a minor refactor to use guard clauses and more comments since there's a lot of loops and conditions here and I find this more maintainable.

Show failed additions and removals in visualizer

---

plugin/src/InstanceMap.lua
plugin/src/PatchTree.lua
plugin/src/Reconciler/applyPatch.lua

- Catch removal failures
- Catch name change failures
- Don't remove IDs for instances if they weren't actually destroyed

Catch more sync failures

---

CHANGELOG.md
plugin/src/Reconciler/diff.lua

This PR closes #841 by ignoring any properties in `Reconciler:diff` that fail to read for any reason. Before, `Reconciler:diff` would simply exit with an error when it encountered properties that failed to read for an unknown reason.

Ignore any unreadable property in Reconciler:diff

---

CHANGELOG.md
plugin/http/Error.lua
plugin/http/init.lua

The `http.get` promise treated any request that made it through the `pcall` without erroring as a success to `resolve`.
`ApiContext` would then check the status code and `reject`, but by then it's too late to handle gracefully and we just show the error code and stop the sync.
This improves that. We create a relevant `Error` object for requests that are not success codes, so that `ApiContext` can handle them correctly.
The immediate impact is that GitHub Codespaces is now compatible with Rojo, since requests to the [forwarded port](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace) receive a [504 Gateway Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) after 100 seconds. Given our long polling, we simply resend …

Catch failed http requests that didn't error so we can handle them correctly

---

CHANGELOG.md
crates/memofs/CHANGELOG.md
crates/memofs/src/lib.rs
src/snapshot_middleware/lua.rs
src/snapshot_middleware/txt.rs

Closes #776 by implementing a new method `Vfs::read_to_string_lf_normalized` and changing the Lua middleware to use it.
I'm not really sure why the middlewares were calling `to_owned` on `contents_str` - could it have been a limitation of earlier rbx-dom versions?

Normalize line endings to LF in Lua middleware

---

plugin/src/App/Components/StringDiffVisualizer/init.lua
plugin/src/App/Components/TableDiffVisualizer/Array.lua
plugin/src/App/Components/TableDiffVisualizer/Dictionary.lua
plugin/src/App/StatusPages/Confirming.lua
plugin/src/App/StatusPages/Settings/Setting.lua
plugin/src/App/StatusPages/Settings/init.lua
plugin/src/PatchTree.lua
plugin/src/Reconciler/init.lua
plugin/src/Settings.lua
plugin/src/Timer.lua

- Mark dev debug settings like we mark experimental settings
- Create dev setting to enable timing logs
- When timing is disabled, timer functions are replaced with a no-op to minimize overhead 
- Add timing logs to major internal actions
- Make patchTree notably faster in a few key areas
- Make confirming page's patch visualizer reduce wasteful work
Also fixed a pet peeve of mine- the back button in the settings menu no longer scrolls off screen so you can now go back without having to scroll back up

Add benchmarking, perf gains, and better settings UI

---

CHANGELOG.md
crates/memofs/CHANGELOG.md
crates/memofs/src/lib.rs
src/snapshot_middleware/lua.rs
src/snapshot_middleware/txt.rs

This PR adds Lua LF normalization to the 7.4.x branch. 
This wasn't a particularly clean cherry pick because the Lua and text middlewares were altered slightly by #813, which did not make it into 7.4. Please double check my conflict resolution and make sure I got it right!

Backport #854 to Rojo 7.4 (Lua LF normalization)

---

rojo-test/build-test-snapshots/end_to_end__tests__build__rbxmx_in_folder.snap
rojo-test/build-test-snapshots/end_to_end__tests__build__unresolved_values.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_all-2.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_subscribe.snap
src/snapshot/tree.rs

This PR closes #628 by adding a change to the 7.4.x branch that inserts `Model.NeedsPivotMigration` when it's missing from any instance that inherits from `Model`.
This is a pretty poor solution, but this bug needs to be fixed for 7.4.1 and the scope of the work in rojo-rbx/rbx-dom#385 (which when closed, will properly fix the underlying problem) is a little too large to comfortably fit into 7.4.1. 
Please make sure I got all the classes, and of course test the changes (I did confirm that they work myself, but it's good to have more sets of eyes)

Insert Model.NeedsPivotMigration in insert_instance when missing

---

CHANGELOG.md
plugin/rbx_dom_lua/EncodedValue.lua
plugin/rbx_dom_lua/allValues.json
plugin/rbx_dom_lua/customProperties.lua
plugin/rbx_dom_lua/database.json

This PR closes #866 by bringing changes over from rojo-rbx/rbx-dom@6ccd30f, fixing incorrectness when serving model pivots.

rbx_dom_lua rojo-rbx/rbx-dom@6ccd30f (custom pivot get/set)

---

Cargo.lock
Cargo.toml
src/main.rs

Closes #855.
This resolves the problem with building Rojo while the `profile-with-tracy` feature is on. I just removed `tracy_client` as a direct dependency of ours and used the re-export that `profiling` provides since it guarantees we'll never be out of sync again.
Provided `profiling` respects semver, this shouldn't have any problems going forward.

Allow building Rojo with `profile-with-tracy` feature

---

CHANGELOG.md
rojo-test/build-test-snapshots/end_to_end__tests__build__no_name_default_project.snap
rojo-test/build-test-snapshots/end_to_end__tests__build__no_name_project.snap
rojo-test/build-test-snapshots/end_to_end__tests__build__no_name_top_level_project.snap
rojo-test/build-tests/no_name_default_project/default.project.json
rojo-test/build-tests/no_name_default_project/src/third-level/default.project.json
rojo-test/build-tests/no_name_project/default.project.json
rojo-test/build-tests/no_name_project/src/bool_value.project.json
rojo-test/build-tests/no_name_top_level_project/default.project.json
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_default_project_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_default_project_info.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_project_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_project_info.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_top_level_project_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_top_level_project_info.snap
rojo-test/serve-tests/no_name_default_project/default.project.json
rojo-test/serve-tests/no_name_default_project/src/third-level/default.project.json
rojo-test/serve-tests/no_name_project/default.project.json
rojo-test/serve-tests/no_name_project/src/bool_value.project.json
rojo-test/serve-tests/no_name_top_level_project/default.project.json
src/project.rs
src/serve_session.rs
src/snapshot_middleware/project.rs
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__no_name_project.snap
tests/tests/build.rs
tests/tests/serve.rs

Unlike most of the other backports, this code couldn't be directly translated so it had to be re-implemented. Luckily, it is very simple. This implementation is a bit messy and heavy handed with potential panics, but I think it's probably fine since file names that aren't UTF-8 aren't really supported anyway. The original implementation is a lot cleaner though.
The test snapshots are (almost) all identical between the 7.5 implementation and this one. The sole exception is with the path in the `snapshot_middleware::project` test, since I didn't feel like adding a `name` parameter to `snapshot_project` in this implementation.

Backport #870 (optional project names) to 7.4.x

---

CHANGELOG.md
rojo-test/build-test-snapshots/end_to_end__tests__build__no_name_default_project.snap
rojo-test/build-test-snapshots/end_to_end__tests__build__no_name_project.snap
rojo-test/build-test-snapshots/end_to_end__tests__build__no_name_top_level_project.snap
rojo-test/build-tests/no_name_default_project/default.project.json
rojo-test/build-tests/no_name_default_project/src/third-level/default.project.json
rojo-test/build-tests/no_name_project/default.project.json
rojo-test/build-tests/no_name_project/src/bool_value.project.json
rojo-test/build-tests/no_name_top_level_project/default.project.json
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_default_project_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_default_project_info.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_project_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_project_info.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_top_level_project_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_top_level_project_info.snap
rojo-test/serve-tests/no_name_default_project/default.project.json
rojo-test/serve-tests/no_name_default_project/src/third-level/default.project.json
rojo-test/serve-tests/no_name_project/default.project.json
rojo-test/serve-tests/no_name_project/src/bool_value.project.json
rojo-test/serve-tests/no_name_top_level_project/default.project.json
src/project.rs
src/serve_session.rs
src/snapshot_middleware/mod.rs
src/snapshot_middleware/project.rs
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__no_name_project.snap
tests/tests/build.rs
tests/tests/serve.rs

Closes #858.
If a project is named `default.project.json`, it acts as an `init` file and gains the name of the folder it's inside of. If it is named something other than `default.project.json`, it gains the name of the file with `.project.json` trimmed off. So e.g. `foo.project.json` becomes `foo`.

Make the `name` field in projects optional

---

plugin/src/PatchTree.lua

I really screwed this one up. Don't know how I managed that.
Tree was being built out of order, but only for some change types. This meant that some changes built a good tree, some built an upside down one. I suppose that's how it slipped past us.

Build tree ancestry correctly

---

plugin/src/App/Components/Tooltip.lua

This ends up being more reliable and less wasteful. GuiState seems to update more reliably than MouseEnter/Leave.
The alternative way to make this more reliable would be to run our manual mouse bounds check every frame, which I'd like to avoid.

Use GuiState instead of manual calculation for tooltips

---

Cargo.lock
Cargo.toml
crates/memofs/Cargo.toml
crates/rojo-insta-ext/Cargo.toml

So, earlier today I got a notification that we had a new security vulnerability open on Rojo. For the curious, it is https://github.com/advisories/GHSA-r8w9-5wcg-vfj7 and I don't think it actually impacts us.
What it made me realize however was that our dependencies were fairly out of date and the version listed in Cargo.toml for most of them was not the version we were actually using and it's been a long time since we just blanket updated things. So, I ran `cargo update` and then changed the version in our `Cargo.toml`s to reflect the version that's now in the `Cargo.lock` file.
This is not something I would recommend we do very often, but Tokio was listed as being `1.12.0` despite us actually using `1.32.0` before this change. We should try to at least be somewhat accurate with our …

Update Cargo dependencies

---

plugin/src/Config.lua

This PR is a very small change that fixes the string pattern that reads the rojo version from `Version.txt`. Currently this reads an extra new-line character which makes reading the version text in the plugin difficult.
It seems the rust side of things already trims the string when comparing, but the lua side does not.
Current:
Fix:
Apologies if I skipped over some process of submitting a bug and / or am basing on the wrong branch etc.

Trim plugin version string

---

Cargo.lock
Cargo.toml
crates/memofs/CHANGELOG.md
crates/memofs/Cargo.toml

This PR bumps memofs' version number to 0.3.0, and also updates Rojo's dependencies on memofs. This is necessary to have Rojo on crates.io actually contain the recent changes in memofs, because crates.io does not support path dependencies.
After this PR is merged, I'll tag the sqaush merge commit as `memofs-v0.3.0`. Then we should run `cargo publish` for memofs. Then, we should cherry pick this same commit onto the `7.4.x` branch, and make a new release for Rojo 7.4.2.

Release memofs 0.3.0, bump Rojo dependency

---

.github/workflows/ci.yml

This PR performs some routine maintenance on our CI workflow:
* Replaces `actions-rs/toolchain` with `dtolnay/rust-toolchain`. The actions at `actions-rs` are no longer maintained, and they use deprecated GitHub Actions APIs. dtolnay's action does not support the `override` option, but we didn't actually need to use it anyway. 
* Upgrades `actions/checkout` to v4, because v3 causes some warnings since it uses Node.js 16, which is deprecated.

Use dtolnay/rust-toolchain and upgrade to checkout v4 in CI workflow

---

.github/workflows/release.yml

This PR performs a number of relatively straightforward maintenance tasks and improvements for the "Release" workflow:
* Upgrades to actions/checkout@v4 and switches to dtolnay/rust-toolchain instead in favor of actions-rs/toolchain
Reasoning is the same as #900 
* Switches to softprops/create-gh-release
actions/create-release is unmaintained and has been archived for more than three years. 
I considered using the GitHub CLI's (which is preinstalled on GitHub-hosted runners)`gh release create` to do this so we wouldn't have to pull in another third-party action, but it requires a checkout first - but doing this only adds a few more seconds before the release is created comapred to create-gh-release, so it may be acceptable?
* Switches to using preinstalled GitHub CLI to upload release …

Release workflow maintenance

---

CHANGELOG.md
crates/memofs/src/lib.rs

This PR closes #899 by changing the implementation of `Vfs::read_to_string_lf_normalized` to use `str::replace` to replace `\r\n` with `\n`, rather than joining the result of `str::lines`. 
This is also a small performance win because less work needs to be done when the file only contains LF line endings, and we never need to collect into an intermediate `Vec<&str>`.

Fix removing trailing newlines by using str::replace in memofs

---

CHANGELOG.md
plugin/src/App/StatusPages/Settings/init.lua
plugin/src/App/init.lua
plugin/src/ServeSession.lua

Locking this setting during sync is unnecessarily restrictive. I usually keep this option on so it's very annoying to have to disconnect when I want to quickly open a script in Studio.

Allow openScriptsExternally option to be changed during sync

---

CHANGELOG.md
plugin/src/InstanceMap.lua
plugin/src/Reconciler/applyPatch.lua
plugin/src/Reconciler/applyPatch.spec.lua

Adopts the latest ChangeHistoryService APIs.  Our Undo/Redo notification warnings (to prevent accidentally undoing a Rojo patch) still work fine with this new API.
Avoids the permanent Destroy action, uses Remove instead. This closes #914.

Use history recording and don't do anything permanent

---

rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_top_level_project_all-2.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__sync_rule_no_name_project_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__sync_rule_no_name_project_info.snap
rojo-test/serve-tests/sync_rule_no_name_project/default.project.json
rojo-test/serve-tests/sync_rule_no_name_project/src/not_a_project.rojo
src/cli/fmt_project.rs
src/project.rs
src/serve_session.rs
src/snapshot_middleware/mod.rs
src/snapshot_middleware/project.rs
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__project__test__no_name_project.snap
tests/rojo_test/serve_util.rs
tests/tests/serve.rs

Closes #916.
Turns out we had a test that should've caught this, it's just that nobody caught it when this feature was implemented. We'll likely want to backport this into the 7.4.x branch as well.
Let me know if you have a better way to calculate project names in the middleware, I'm not in love with the way it's implemented here.

Correct issue with default.project.json files with no name being named `default` after change

---

tests/rojo_test/serve_util.rs

This PR adds a 100ms sleep between copying test files and starting the Rojo server in macOS serve tests. I added a comment explaining the addition - I'm not sure why it happens, there's very scant information about this issue on the internet, and this isn't quite a proper way to fix it. Ideally, we could somehow get FSEvents to flush its event stream before starting to process events, but that will probably require changes to notify.

Sleep between file copies and serve for macOS serve tests

---

CHANGELOG.md
crates/memofs/src/lib.rs
plugin/src/App/StatusPages/Settings/init.lua
plugin/src/App/init.lua

As part of prep for a 7.4.2 release, this backports changes to the 7.4.X branch that we can reasonably ship in 7.4.2 without too many code changes.

Backport #893 and #903 to Rojo 7.4

---

rojo-test/serve-test-snapshots/end_to_end__tests__serve__no_name_top_level_project_all-2.snap
src/cli/fmt_project.rs
src/project.rs
src/serve_session.rs
src/snapshot_middleware/project.rs
tests/rojo_test/serve_util.rs
tests/tests/serve.rs

This backports the bugfix made in 917 to the 7.4.x branch. I'm not sure that this was even a bug in 7.4.x (the implementation was different so it may have not been) but this should guarantee it isn't.

Backport #917 to Rojo 7.4.x branch

---

Cargo.lock
Cargo.toml
plugin/rbx_dom_lua/customProperties.lua
plugin/rbx_dom_lua/database.json

Standard rbx_dom update.
I honestly just straight up forgot to fix the setter/getter for `WorldPivotData`; it should be an alias in the database, ideally. It'll be fixed in rbx-dom's repo, as I've opened an issue for it here: https://github.com/rojo-rbx/rbx-dom/issues/430
Since it'll require a change to the database, I'm gonna leave it be for now though. No harm no foul.

Update rbx_dom for 7.4.x branch

---

CHANGELOG.md
aftman.toml
plugin/src/Reconciler/setProperty.lua

When sent through the network, NaN and Infinity become `nil` due to JSON not supporting them. This results in two problems:
- An annoying `value of type nil cannot be converted to number` warning in the output
- The value being reset to `0` instead of whatever value it was before
Neither of these are desirable, so this PR fixes that behavior. It does so by explicitly ignoring `nil` updates for `Float32` and `Float64` updates. This is explicitly on the 7.4.x branch because I don't want it to become permanent. Long-term, we want to swap to a different network protocol which should fix this issue.
See #953 for some discussion on this subject.

In the plugin, don't write properties if they're nil and also a number

---

.gitattributes

This PR sets linguist language of lua files to luau for syntax highlighting on github.

Set linguist language of lua files to luau

---

rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_patch_update_all-2.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_patch_update_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_patch_update_info.snap
src/snapshot/patch_compute.rs
tests/tests/serve.rs

Closes #929.
It turns out the underlying issue was that we weren't accounting for ref properties at all in the patch computation. This resolves that issue by just collecting them during `compute_property_patch`.
Of note, I've decided to just reuse the `ref_properties` test files for this since it's ultimately academic either way. It adds noise to the snapshot files but I think it's fine because the only thing that really matters here is the `messageCursor` on the return from the read endpoint. Let me know if you'd prefer a cleaner snapshot.

Actually include attribute-defined properties in patch computation

---

.github/workflows/changelog.yml
.github/workflows/ci.yml
.github/workflows/release.yml
aftman.toml
src/change_processor.rs
src/cli/sourcemap.rs

- Update the `setup-aftman` action to `v0.4.2` instead of using `v0.1.0` or `v0.3.0`
- Start using Aftman v0.2.8
- Update tools versions in the Aftman.toml file
- Fix clippy lints in a few files
- Update version of `actions/checkout` to `v4` in our changelog check

Update workflow and tooling versions

---

CHANGELOG.md
src/project.rs
src/snapshot_middleware/json_model.rs
src/snapshot_middleware/meta_file.rs

Closes #972.
This is a trivial change: we just add an unused `$schema` field to all of the JSON structs.

Support `$schema` in JSON structures

---

Cargo.toml
src/snapshot/patch_apply.rs
src/snapshot/patch_compute.rs
src/snapshot/tests/apply.rs
src/snapshot/tests/compute.rs
src/snapshot_middleware/csv.rs
src/snapshot_middleware/dir.rs
src/snapshot_middleware/json.rs
src/snapshot_middleware/lua.rs
src/snapshot_middleware/project.rs
src/snapshot_middleware/toml.rs
src/snapshot_middleware/txt.rs
src/web/ui.rs

I'm tired of this macro. It will cause us trouble down the line when we try to swap to a faster hashmap, and it's just not idiomatic.
So, I have removed it. In practice this mostly impacts tests.

Remove maplit dependency and stop using a macro for hashmaps

---

CHANGELOG.md
plugin/src/App/init.lua

Closes #986.
The sync reminder notification will now tell you what you synced and when you synced it.
Example: `You synced project 'LuaLearning' to this place 2 hours ago. Would you like to reconnect?`
If there's no known project name, it'll fallback to: `You synced localhost:34872 to this place 2 hours ago. Would you like to reconnect?`
This should only happen once per place, since the existing save data you have before this update didn't store the project name.

Make sync reminder more detailed

---

plugin/src/App/Components/Checkbox.lua
plugin/src/App/Components/Dropdown.lua
plugin/src/App/Components/Tooltip.lua
plugin/src/App/StatusPages/Settings/Setting.lua
plugin/src/App/StatusPages/Settings/init.lua

Adds the ability to define descriptive tooltips for settings when they are locked.
Makes some minor improvements to tooltip layout logic as well.

Add locked tooltip

---

plugin/src/App/Notifications.lua

Changes:
- The width of the notification will be the minimum space required. (It used to do this, but was broken in #988.)
- The text is centered, making single line notifs feel less unbalanced.
Before & After:
- The text wrapping no longer shifts around as the notification animates in.
Before & After: (Slowed to show the effect more clearly)
https://github.com/user-attachments/assets/957e692f-9807-4b17-b52e-07f7cc427653
https://github.com/user-attachments/assets/c6c7df0f-df2e-4ec4-b10f-ff8f7f42ec17

Improve notification layout

---

CHANGELOG.md

Appears in the last 7.4.4 release we forgot to add the changelog entry into master. We stay silly.

Add missing CHANGELOG entry for 7.4.4

---

CHANGELOG.md
rojo-test/build-test-snapshots/end_to_end__tests__build__init_meta_class_name.snap
rojo-test/build-test-snapshots/end_to_end__tests__build__rbxmx_in_folder.snap
rojo-test/build-test-snapshots/end_to_end__tests__build__unresolved_values.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_all-2.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__empty_json_model_subscribe.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__model_pivot_migration_all-2.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__model_pivot_migration_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__pivot_migration_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__pivot_migration_info.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_all-2.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_patch_update_all-2.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_patch_update_all.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_patch_update_subscribe.snap
rojo-test/serve-test-snapshots/end_to_end__tests__serve__ref_properties_subscribe.snap
rojo-test/serve-tests/pivot_migration/Tool.model.json
rojo-test/serve-tests/pivot_migration/default.project.json
src/snapshot/patch_apply.rs
src/snapshot/patch_compute.rs
src/snapshot/tree.rs
tests/tests/serve.rs

This exists on 7.4.x but never made it to master by my own instruction. We have not fixed it upstream yet, so we need to make sure it's in subsequent releases of Rojo.
Skipping the changelog on this because it's been in the last 4 releases.

Re-add the hack to write NeedsPivotMigration as `false` for models

---

.github/workflows/release.yml

May have consequences - it's possible that the binary will be ran on systems with an out-of-date glibc

Change release build linux version to ubuntu-latest

---

Cargo.toml
crates/memofs/Cargo.toml

Suggested by Lucien, we should add the current maintainers to the Authors field of the Cargo.tomls
Nobody but Lucien has contributed to `cargo-insta-ext` yet, but this adds @kennethloeffler and myself to the Authors field for Rojo and memofs.

Add current maintainers to author field of Cargo.toml files

---

plugin/src/App/StatusPages/Error.lua

The Error page in the plugin should have the same brand header as all the other pages. This means that when people send a screenshot of the error, we don't have to always ask them what version they are on.

Show the plugin version on the Error page

---

CHANGELOG.md
plugin/src/App/Components/Header.lua
plugin/src/App/Components/Tooltip.lua
plugin/src/App/init.lua
plugin/src/Version.lua

If you have the `Check For Updates` setting enabled, it currently only gives you a notification when you first open Studio. If you opened Studio in the background, it's possible to miss this.
I've added an update indicator to the version in the `Header` that's on every page. This way, you cannot miss it and it also makes it easy to spot old versions still being used in bug reports.
(It looks normal when there's no update or you disable the update check)
Also, I added an optional `delay` prop to Tooltip triggers and added 24 hour caching to the GitHub releases check (because otherwise it would make a request every time you switch pages and trigger a Header render).

Show update indicator on version header

---

.github/workflows/ci.yml
.github/workflows/release.yml

Caches the rust dependencies (`~/.cargo/registry`, ` ~/.cargo/git`, `output`) used for compiling in the release.yml. It uses the matrix os and a hash of the Cargo.lock file in the key.

Cache Rust Dependencies in release.yml.

---

CHANGELOG.md
assets/index.css

closes #839
This does not add a dark theme to the server website, but that's more complicated than just adding a CSS property. 
Before:
After:

Change background color of web UI to gray

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/snapshot_middleware/mod.rs
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__yaml__test__instance_from_vfs-2.snap
src/snapshot_middleware/snapshots/librojo__snapshot_middleware__yaml__test__instance_from_vfs.snap
src/snapshot_middleware/yaml.rs

Supersedes #913
The motivation is the same as the old PR: Since we support both JSON and TOML, it seems reasonable to support the third of the config-file brothers, YAML. This support is added as both `.yml` and `.yaml`.
This is implemented using `rust-yaml2` rather than `serde-yaml` because the latter is currently unmaintained, and we don't really need it. The code turns out to be very similar to what it was in 913, which used `serde-yaml`.
Support for multiple documents in a file is left as an error right now. We could conceivably make multi-document files resolve into a table of tables, but that's something we can revisit later. This is a safe default right now and prevents people from accidentally including multi-document files.

Add YAML middleware that behaves like TOML and JSON

---

src/main.rs

We get a lot of bug reports that are just people posting the crash they got from Rojo. Including the version number will make debugging those faster, as we'll be able to tell immediately if someone is running an out of date version.

Put Rojo version in crash message

---

CHANGELOG.md
CONTRIBUTING.md

I've found and fixed a couple of typos/grammar errors while reading through the docs:
1. propertyes -> properties in `CHANGELOG.md`
2. "problems in documentation" -> "problems in the documentation" in `CONTRIBUTING.md`
> These are only minor changes. Expect no semantic change.

Fix a grammar error and a typo

---

CHANGELOG.md
src/cli/init.rs

Closes #1107, supersedes #1108 
Implements a flag to skip initializing the git repository when running `init`. Straightforward after the refactor.

Add flag for skipping git initialization to `init` command
