server/src/fs_watcher.rs
server/src/imfs.rs
server/src/message_queue.rs
server/src/project.rs
server/src/rbx_session.rs
server/src/session.rs
server/src/session_id.rs
server/src/web.rs

I used cargo clippy and fixed whatever it warned about. Not sure how much of the warnings were up to personal preference (or if any of this code doesn't work and there's an oversight in clippy). I haven't tested this.

Fixed clippy warnings

---

server/src/message_queue.rs
server/src/web/api.rs

Fixes #137.
This PR replaces the bad `MessageQueue` implementation with one that's still pretty bad but should be significantly more robust. It changes the queue's listeners to be oneshot channels (they unsubscribe automatically) and removes the ability to explicitly unsubscribe (just drop your `Receiver`).

Rewrite message queue with oneshot futures

---

docs/installation.md

Also changed verbiage from "add partitions" to "sync files"

Update mention of VS Code extension in docs

---

docs/installation.md

Fix repeated "available available"

Minor typo fix

---

docs/guide/new-game.md

Corrected folder name.

---

docs/guide/installation.md
docs/guide/new-game.md
docs/why-rojo.md

part 2 of my docs pull requests.

Correct capitalization/typos

---

src/snapshots/serve_session__change_txt_file_after.snap

Broke with https://github.com/rojo-rbx/rojo/commit/30351f7b9dd8ab2540d6fde42e904b445adeb3eb

Fix failing snapshot test

---

Cargo.toml
plugin/src/ApiContext.lua
plugin/src/DevSettings.lua
plugin/src/InstanceMap.lua
plugin/src/ServeSession.lua
src/change_processor.rs
src/serve_session.rs
src/web/api.rs
src/web/interface.rs

The goal of this PR is to land an opt-in version of two-way sync for scripts behind a flag.
A lot of the foundational work for this is already done, but this is going to be tough, and feedback is welcome from anyone!

Two way sync V0

---

plugin/http/Error.lua

This uses an em dash instead of double lines (--)

fix hyphen

---

src/snapshot_middleware/rbxm.rs
src/snapshot_middleware/rbxmx.rs

Reword top level model error message

---

CONTRIBUTING.md

I was pretty confused for a while about the missing submodules, so I figured I'd add this to help others in the future. I've never used submodules before so if I'm using the wrong command to load them, lmk and I can update.

Add git submodules info to CONTRIBUTING.md

---

selene.toml
testez.toml

Almost all of the errors that are reported by selene relate to TestEZ. This PR reduces the error count from 175 down to 1.

Add TestEZ std to selene

---

CHANGELOG.md

Fix link to v7.2.1 in the changelog

---

plugin/src/App/init.lua

Adds a bit of UI Padding which makes the notifications look better
**Before:**
**After:**

Add uipadding to notifications

---

assets/default-place-project/default.project.json

Renamed Common to Shared

---

src/snapshot_middleware/meta_file.rs

copyed over the implementation from DirectoryMetadata

added attributes to AdjacentMetadata

---

src/change_processor.rs

fixes Dir write firing whole chain when a file inside the directory was added or removed.

fix_vfs_double_update

---

plugin/src/App/init.lua

Reduce minimum plugin size

---

CHANGELOG.md

Forgot to update changelog in those PRs, this remedies that

Add PRs 674 and 675 to changelog

---

src/change_processor.rs

Bear with me here...
The first in a series of PRs that aim to get CI passing

Fix change processor clippy lints

---

src/cli/fmt_project.rs
src/cli/init.rs
src/cli/serve.rs
src/cli/upload.rs

The second in a series of PRs that aim to get CI passing

Fix cli clippy lints

---

crates/memofs/src/in_memory_fs.rs
crates/memofs/src/lib.rs
crates/memofs/src/noop_backend.rs
crates/memofs/src/std_backend.rs

The third in a series of PRs that aim to get CI passing

Fix memofs clippy lints

---

src/project.rs

The fourth in a series of PRs that aim to get CI passing

Fix project clippy lints

---

src/serve_session.rs

The fifth in a series of PRs that aim to get CI passing

Fix serve session clippy lints

---

src/snapshot/patch_apply.rs
src/snapshot/patch_compute.rs
src/snapshot/tree.rs

The sixth in a series of PRs that aim to get CI passing

Fix snapshot clippy lints

---

src/snapshot_middleware/dir.rs
src/snapshot_middleware/util.rs

The seventh in a series of PRs that aim to get CI passing

Fix snapshot middleware clippy lints

---

build.rs
src/lua_ast.rs
src/path_serializer.rs
src/web/interface.rs

The eighth (and final) in a series of PRs that aim to get CI passing

Fix remaining clippy lints

---

CHANGELOG.md

Update changelog to include #713

---

.github/workflows/ci.yml

This pr adds a check for changelog file changes on pull request.
`no changelog` label for skip

(feat) Add Changelog Check Action

---

plugin/src/App/init.lua
plugin/src/ServeSession.lua

Expose reconciler hooks on servesession

---

CHANGELOG.md
src/web/api.rs

After seeing an issue with the opener not opening, it was strange to see that there was no logging or error handling! This PR aims to solve that.

Add some logging/error-handling for opener errors!

---

Cargo.lock
Cargo.toml
plugin/rbx_dom_lua/EncodedValue.lua
plugin/rbx_dom_lua/allValues.json
plugin/rbx_dom_lua/customProperties.lua
plugin/rbx_dom_lua/database.json

Like it says on the tin, updates the dependencies from rbx_dom.

Update rbx_dom dependencies

---

plugin/rbx_dom_lua/EncodedValue.lua

rbx_dom_lua rojo-rbx/rbx-dom@0e10232b (SecurityCapabilities)

---

CHANGELOG.md

Summarizes recent changes since 7.4.0-rc2 in the changelog

Update changelog in preparation for 7.4.0-rc3

---

build.rs
src/multimap.rs
src/web/api.rs

No substance changes, but these borrows weren't necessary so I'm getting rid of them!

Remove unnecessary borrows

---

CHANGELOG.md
plugin/http/Error.lua
plugin/http/init.lua

This PR adds a fix for gateway timeout handling to the 7.4.x branch

Backport #847 to 7.4 (gracefully handle gateway timeouts)

---

CHANGELOG.md
plugin/rbx_dom_lua/EncodedValue.lua
plugin/rbx_dom_lua/allValues.json
plugin/rbx_dom_lua/customProperties.lua
plugin/rbx_dom_lua/database.json

This PR backports some changes to rbx_dom_lua to fix serving model pivots

Backport #868 to 7.4 (custom pivot geter/setter)

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml

Migrate to using Rustls

---

CHANGELOG.md

This PR edits the changelog on master to reflect 7.4.1's release

Update master's changelog in preparation for 7.4.1 release

---

CHANGELOG.md
plugin/src/App/StatusPages/Settings/init.lua
plugin/src/App/init.lua

Closes #891, this PR adds Never option to confirmation behavior

Add never option to Confirmation

---

Cargo.lock
Cargo.toml
crates/memofs/CHANGELOG.md
crates/memofs/Cargo.toml

Backports the release of memofs v0.3.0

Update memofs in 7.4.x branch

---

CHANGELOG.md

After 7.4.3 released, I forgot to update the changelog on master. This fixes that.

Add 7.4.3 to changelog

---

Cargo.lock
Cargo.toml
plugin/rbx_dom_lua/customProperties.lua
plugin/rbx_dom_lua/database.json

This PR updates all rbx-dom dependencies to their latest versions.

Update rbx-dom dependencies

---

build.rs

Ignore .git directory when building VfsSnapshot in build script

---

CHANGELOG.md
plugin/src/PatchTree.lua
plugin/src/Reconciler/diff.lua

Fixed nil -> nil props showing up as failing in patch visualizer (plugin)
